# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  check:
    desc: Run all pre-commit hooks
    cmds:
      - pre-commit run -a

  pre-commit:
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  test:
    desc: Run python test and coverage
    cmds:
      - pytest --cov=pdh .

  build:
    desc: "Build python wheel"
    cmds:
      - poetry build

  publish:
    desc: "Publish wheel to pypi"
    cmds:
      - poetry publish -u $PYPI_USERNAME -p $PYPI_TOKEN
    deps:
      - build

  clean:
    desc: Cleanup
    cmds:
      - rm -rf ./dist

  nix:build:
    desc: Build nix derivation
    cmds:
      - nix build --json | jq -r '.[].outputs | to_entries[].value' | cachix push pdh
      - nix flake archive --json | jq --raw-output '.path, (.inputs | to_entries [] .value.path)' | cachix push pdh
