name: Release
on:
  push:
    tags: ["v*"]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-task@v1

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run arbitrary commands
        run: devbox run check

      - name: Run a script called test
        run: devbox run test


  build:
    permissions:
      id-token: write
      contents: write
    name: "Build & Push wheel"
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-task@v1

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run a script called test
        run: devbox run build

      - name: Release to pypi
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*
            LICENSE